#!/bin/bash

npx google-closure-compiler \
--language_in ECMASCRIPT5_STRICT \
--language_out ECMASCRIPT5_STRICT \
--warning_level DEFAULT \
--compilation_level WHITESPACE_ONLY \
--isolation_mode IIFE \
--js "./../../lib/rune.js" \
--js "./../../src/scope/Manifest.js" \
--js "./../../src/data/resource/Requests.js" \
--js "./../../src/ui/hud/PlayerHud.js" \
--js "./../../src/handler/collision/CollisionHandler.js" \
--js "./../../src/room/Room.js" \
--js "./../../src/projectile/Projectile.js" \
--js "./../../src/projectile/arrow/Arrow.js" \
--js "./../../src/projectile/spell/Spell.js" \
--js "./../../src/drops/coin/Coin.js" \
--js "./../../src/particle/blood/Blood.js" \
--js "./../../src/particle/bodyparts/goblin/GoblinHead.js" \
--js "./../../src/particle/bodyparts/goblin/GoblinChunk.js" \
--js "./../../src/entity/Entity.js" \
--js "./../../src/entity/hero/PlayableCharacter.js" \
--js "./../../src/entity/hero/Wizard.js" \
--js "./../../src/entity/enemy/Enemy.js" \
--js "./../../src/entity/enemy/Goblin.js" \
--js "./../../src/entity/enemy/Slime.js" \
--js "./../../src/player/Player.js" \
--js "./../../src/player/PlayerOne.js" \
--js "./../../src/player/PlayerTwo.js" \
--js "./../../src/scene/menu/Menu.js" \
--js "./../../src/scene/game/Game.js" \
--js "./../../src/scene/gameover/GameOver.js" \
--js "./../../src/system/Main.js" \
--js "./../../src/scope/Alias.js" \
--js_output_file "./../../dist/howlkraul.js";